version: "2"
run:
  modules-download-mode: readonly
linters:
  enable:
    - bodyclose
    - contextcheck
    - errcheck
    - ginkgolinter
    - gocritic
    - gomodguard
    - govet
    - gosec
    - importas
    - loggercheck
    - makezero
    - misspell
    - nonamedreturns
    - nosprintfhostport
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    gocritic:
      disabled-checks:
        - singleCaseSwitch
    gomodguard:
      blocked:
        modules:
          - github.com/go-errors/errors:
              recommendations:
                - github.com/pkg/errors
          - github.com/ghodss/yaml:
              recommendations:
                - sigs.k8s.io/yaml
          - github.com/hashicorp/multierror:
              recommendations:
                - errors
          - gopkg.in/yaml.v2:
              recommendations:
                - sigs.k8s.io/yaml
          - gopkg.in/yaml.v3:
              recommendations:
                - sigs.k8s.io/yaml
          - io/ioutil:
              recommendations:
                - io
                - os
    misspell:
      locale: US
    nonamedreturns:
      report-error-in-defer: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
issues:
  fix: true
formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/Kong/shared-speakeasy)
      custom-order: true
  exclusions:
    generated: lax
