package kumalabels

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
)

var _ basetypes.MapTypable = KumaLabelsMapType{}

const kongMeshSystemNamespace = "kong-mesh-system"

// taken from https://github.com/kumahq/kuma/blob/99d5d12d1a67c76ec3d4f992486900b970f85a10/pkg/core/resources/model/labels/labels.go#L8
// AllComputedLabels maps label keys to conditions that determine when they are autogenerated.
// The condition function receives all labels and returns true if the label should be filtered (is autogenerated).
var AllComputedLabels = map[string]func(map[string]attr.Value) bool{
	"kuma.io/mesh":          alwaysAutogenerated,
	"kuma.io/origin":        alwaysAutogenerated,
	"kuma.io/zone":          alwaysAutogenerated,
	"kuma.io/env":           alwaysAutogenerated,
	"k8s.kuma.io/namespace": alwaysAutogenerated,
	"kuma.io/policy-role":   alwaysAutogenerated,
	"kuma.io/proxy-type":    alwaysAutogenerated,
	"kuma.io/sidecar-injection": func(labels map[string]attr.Value) bool {
		// Autogenerated when k8s.kuma.io/namespace is kongMeshSystemNamespace
		if nsVal, ok := labels["k8s.kuma.io/namespace"]; ok {
			if strVal, ok := nsVal.(basetypes.StringValue); ok && !strVal.IsNull() && !strVal.IsUnknown() {
				return strVal.ValueString() == kongMeshSystemNamespace
			}
		}
		return false
	},
}

// alwaysAutogenerated is a helper function for labels that are always autogenerated regardless of other labels.
func alwaysAutogenerated(labels map[string]attr.Value) bool {
	return true
}

type KumaLabelsMapType struct {
	basetypes.MapType
}

func (t KumaLabelsMapType) String() string {
	return "KumaLabelsMapType"
}

func (t KumaLabelsMapType) Equal(o attr.Type) bool {
	other, ok := o.(KumaLabelsMapType)
	if !ok {
		return false
	}
	return t.MapType.Equal(other.MapType)
}

func (t KumaLabelsMapType) ValueFromMap(ctx context.Context, in basetypes.MapValue) (basetypes.MapValuable, diag.Diagnostics) {
	if in.IsNull() {
		return KumaLabelsMapValue{MapValue: basetypes.NewMapNull(types.StringType)}, nil
	}

	allLabels := in.Elements()
	filteredElements := make(map[string]attr.Value)
	for key, val := range allLabels {
		conditionFn, exists := AllComputedLabels[key]
		// Include the label if it's not in AllComputedLabels or if the condition returns false (not autogenerated)
		if !exists || !conditionFn(allLabels) {
			filteredElements[key] = val
		}
	}

	filteredMapValue, diags := types.MapValue(types.StringType, filteredElements)
	if diags.HasError() {
		return nil, diags
	}

	return KumaLabelsMapValue{MapValue: filteredMapValue}, nil
}

func (t KumaLabelsMapType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if !in.IsKnown() || in.IsNull() {
		return KumaLabelsMapValue{MapValue: basetypes.NewMapNull(types.StringType)}, nil
	}

	attrValue, err := t.MapType.ValueFromTerraform(ctx, in)
	if err != nil {
		return nil, err
	}

	mapValue, ok := attrValue.(basetypes.MapValue)
	if !ok {
		return nil, fmt.Errorf("unexpected value type of %T", attrValue)
	}

	val, diags := t.ValueFromMap(ctx, mapValue)
	if diags.HasError() {
		return nil, fmt.Errorf("error filtering KumaLabelsMapType: %v", diags)
	}

	return val, nil
}

func (t KumaLabelsMapType) ValueType(ctx context.Context) attr.Value {
	return KumaLabelsMapValue{}
}

type KumaLabelsMapValue struct {
	basetypes.MapValue
}

func (t KumaLabelsMapValue) Type(ctx context.Context) attr.Type {
	return KumaLabelsMapType{
		MapType: types.MapType{
			ElemType: types.StringType,
		},
	}
}

func (v KumaLabelsMapValue) Equal(o attr.Value) bool {
	other, ok := o.(KumaLabelsMapValue)
	if !ok {
		return false
	}
	return v.MapValue.Equal(other.MapValue)
}
