name: Tag & Release Go Submodule

on:
  workflow_dispatch:
    inputs:
      module:
        description: 'Module subdirectory (e.g., hooks/mesh_defaults)'
        required: true
      version:
        description: 'Version to release (e.g., v1.2.0)'
        required: true

jobs:
  tag-release:
    name: Tag & Release
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Validate inputs
        run: |
          MODULE="${{ github.event.inputs.module }}"
          VERSION="${{ github.event.inputs.version }}"

          # Check if module path exists and has go.mod
          if [ ! -f "$MODULE/go.mod" ]; then
            echo "❌ Module '$MODULE' does not exist or is missing go.mod"
            exit 1
          fi

          # Validate version format (e.g., v1.2.3)
          if ! [[ "$VERSION" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "❌ Version '$VERSION' is not a valid semver (expected format: vMAJOR.MINOR.PATCH)"
            exit 1
          fi

          TAG="${MODULE}/${VERSION}"
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "❌ Tag '$TAG' already exists. Aborting."
            exit 1
          fi

          echo "✅ Inputs validated: module='$MODULE', version='$VERSION'"
      - name: Create tag and GitHub release
        uses: ncipollo/release-action@440c8c1cb0ed28b9f43e4d1d670870f059653174 # v1.16.0
        with:
          tag: ${{ github.event.inputs.module }}/${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.module }} ${{ github.event.inputs.version }}
          body: |
            Automated release for module **${{ github.event.inputs.module }}**
            Version: **${{ github.event.inputs.version }}**
          commit: ${{ github.sha }}
          draft: false
          prerelease: false
